"""Validate external (non-experiment) reports using the same reviewer panel.

Useful for spot-checking the system against the 3 reports from the original
Module 3 LAB (`/Users/zhuricardo/Desktop/GitHub/5481/reports/`). These were
generated by a smaller local Ollama model (llama3.2:1b), so they probe a
different point in the quality space than the in-experiment reports.

Run:
    python -m src.validate_external

This is NOT part of the statistical experiment. It only confirms that the
reviewer panel produces sensible scores on independently-generated artifacts.

CAVEAT: The LAB reports were generated against a different live USGS query than
the cached digest we provide to the reviewer. As a result, the
`factual_grounding` dimension will be artificially low, since the report's
numbers won't match OUR digest. The other 4 dimensions are still meaningful
(structure, actionability, clarity, calibration are intrinsic to the report).
"""
from __future__ import annotations

import json
from pathlib import Path

from .config import REVIEWER_IDS, OUTPUT_DIR, SCORE_KEY, REVIEW_WEIGHTS
from .data_variants import load_variant
from .reviewer import run_reviewer

# Use the largest variant (full 30-day window) as the digest reference.
EXTERNAL_DIGEST_VARIANT = 3

EXTERNAL_REPORTS = [
    "/Users/zhuricardo/Desktop/GitHub/5481/reports/prompt_v1_report.md",
    "/Users/zhuricardo/Desktop/GitHub/5481/reports/prompt_v2_report.md",
    "/Users/zhuricardo/Desktop/GitHub/5481/reports/prompt_final_report.md",
]

OUT_DIR = OUTPUT_DIR / "external_validation"


def validate_one(report_path: Path) -> dict:
    digest = load_variant(EXTERNAL_DIGEST_VARIANT)
    text = report_path.read_text(encoding="utf-8")
    scores = {}
    full = {}
    for rid in REVIEWER_IDS:
        result = run_reviewer(rid, digest=digest, report_md=text)
        scores[rid] = result.get(SCORE_KEY, 0.0)
        full[rid] = result
    composite = sum(REVIEW_WEIGHTS[r] * scores[r] for r in REVIEWER_IDS)
    return {
        "report": str(report_path),
        "scores": scores,
        "composite": round(composite, 3),
        "full": full,
    }


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    summary = []
    print(f"{'Report':50s}  Composite  Per-dimension scores")
    print("-" * 95)
    for rp in EXTERNAL_REPORTS:
        path = Path(rp)
        if not path.exists():
            print(f"  SKIP (not found): {path}")
            continue
        result = validate_one(path)
        scores_inline = "  ".join(f"{r[:4]}={result['scores'][r]:.1f}"
                                  for r in REVIEWER_IDS)
        print(f"{path.name:50s}  {result['composite']:6.2f}    {scores_inline}")
        summary.append({
            "report": path.name,
            "composite": result["composite"],
            "scores": result["scores"],
        })
        # Save full
        out = OUT_DIR / f"{path.stem}__validation.json"
        out.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print("-" * 95)
    (OUT_DIR / "summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    print(f"\nDetailed outputs in: {OUT_DIR}")


if __name__ == "__main__":
    main()
